name: Build and Test

on: push

jobs:

  container-job:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
            POSTGRES_DB: chitter_test
            POSTGRES_HOST: postgres
            POSTGRES_PORT: 5432

  test:
    # Setup vm
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      # This step installs the Python version we want
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.0

      # This step installs pip, pipenv, and our dependencies
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      
      - name: Test with pytest
        run: |
          pipenv run pytest
        env:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          POSTGRES_DB: chitter_test