name: Build and Test

on: push

jobs:

  test:
    # Setup vm
    runs-on: ubuntu-latest
    env:
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      # This step installs the Python version we want
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.0

      # This step installs pip, pipenv, and our dependencies
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      
      - name: Test with pytest
        run: |
          pipenv run pytest
